# Generated by Django 6.0.1 on 2026-01-30 16:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100)),
                ('birth_date', models.IntegerField(validators=[django.core.validators.MinValueValidator(1920), django.core.validators.MaxValueValidator(2025)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1400), django.core.validators.MaxValueValidator(2024)])),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.employee')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('count', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(30)])),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100)),
                ('birth_date', models.IntegerField(validators=[django.core.validators.MinValueValidator(1920), django.core.validators.MaxValueValidator(2025)])),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.schoolclass')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
